### ISSUE TITLE
Autistic isn't a slur

### ISSUE THREAD

**Issue by aidan-fitz** [retextjs/retext-equality#56] opened 2018-10-10 00:21 UTC
"Autistic" is a valid way to refer to a person with autism and should be preferred to "person with autism spectrum disorder", not the other way around. Autism is a disability, not a mental disorder.

**Comment by hrb56** [comment] 2018-10-10 00:32
Also, most autistic people, like myself, think that autism shapes their personality and character. Check out this video for more information: https://www.youtube.com/watch?v=d69tTXOvRq4

**Comment by Murderlon** [comment] 2018-10-10 08:36
Resolved in #57

**Closed by Murderlon** 2018-10-10 08:36 UTC

**Comment by mengsarah** [comment] 2020-09-27 22:16
Hello! I just found this repo and I really like it. But I feel the need to say that unfortunately, "autistic" is absolutely used as a slur by presumably neurotypical people. It's usually used to mean something like these:
* "extremely pedantic (in a way that annoys me)"
* "self-absorbed" (probably a negative interpretation of infodumping)
* even just "annoying (to me) (because I usually deal with people who aren't like you)"

☹️ 

I know that "autistic" is used by many autistic people for themselves, but _mechanically_ speaking, I think "autistic" is similar to "queer" or "gay" in that they are used as slurs by people who don't identify as such and are happy to discriminate against others.

While I'm at it, "disabled" is in a similar situation. Check out the comments on this article (and please don't take any of the ideas proposed in the article itself... it seems to be an oddball on the website): https://blog.easterseals.com/12-different-ways-to-say-disabled/
And also search on Google for "disabled identity word". The word "disabled" is being used by disabled people similar to how "autistic" is being used by autistic people. (To my knowledge, this is only the case for the word "disabled" and not for other words like "invalid" or "handicapped".)

I don't know what the solution here and for other words in similar situations would be. Perhaps a warning saying something like `make sure 'autistic' refers to the diagnosis and is not being used as a replacement for words like 'annoying'`?

My background: I am not autistic, and I was abled for most of my life. Even now, I feel I'm on the fringe of disability. However, I've been doing a lot of reading of various disability narratives, including those of autistic people, for the last 6 years as disability and autism in particular have always been close to my heart (not for "outside uninvolved savior" reasons, or at least I hope not anyway, but I'm hesitant to divulge more info) and I grew up fairly sheltered and didn't think to look up narratives from actually disabled people until about 6 years ago when I was in high school.

Thank you for your time.

**Comment by hrb56** [comment] 2020-09-27 23:27
I'm autistic and most of the autistic communities I'm in strongly prefer to refer to themselves as an autistic person rather than a person with autism. The reason for this is because autistic people strongly prefer to use identity-first language and don't consider their autism to be something that they can just "cure". Autistic people, at least the ones I've encountered, are also strong proponents of neurodiversity, in which society embraces all kinds of minds, especially neurotypes that are continuously marginalized.

**Comment by mengsarah** [comment] 2020-09-28 00:17
I definitely understand that, and I'm not disputing that "autistic" should be used to describe actually autistic people. The problem is that there are presumably non-autistic people who are using "autistic" as a slur or at least as an insult, such as in the following phrases, all of which I have seen used against who I assume were random people or were used against inanimate objects (trigger warning for upsetting language usage):

* "Stop being so autistic. No one cares." in the context of someone explaining the nuances of the differences between two words
* "Wow, your spreadsheet is so autistic. This level of detail is hideous."
* "You're dumber than an autistic child"
* "This website is being autistic" in the context of a website being frustrating to use or making no logical sense
* "This game is so autistic" in the context of a game being unenjoyable
* There's also the "autistic screeching" meme which I have seen used against people who had not disclosed that they were neurodiverse as well as used as some way to bond over some kind of "what a laughingstock, don't be like this person" feeling

Mechanically speaking, it's kind of like how it's okay to describe someone as "gay" even if you're not gay as long as you just mean it as a matter of fact, but it's not okay to use "gay" as an insult, like "That's so gay", and a lot of people unfortunately still use "gay" as an insult.

Since there's currently no easy way (or any way at all, in some cases) for any tool to check if these labels are being used neutrally or if they're being used in a derogatory manner, I'm not sure what should be done about this kind of situation, so I was thinking maybe a warning of some kind might suffice, like `make sure that this word is referring to the diagnosis and is not being used as a replacement for words like 'annoying'`

**Comment by aidan-fitz** [comment] 2020-09-28 23:21
Yeah, I absolutely agree that "autistic" is often used as a slur (having witnessed it myself) and that there should be some kind of warning about it. I removed the original "autistic" rule (in #57) because it was flagging all usages of the word "autistic" regardless of whether they were benign or offensive, but I see the case for creating a new set of rules. I don't know if retext currently supports more advanced NLP techniques for distinguishing offensive from benign usage, but we could:

- Display an error for clearly offensive usages such as `autistic screeching`.
- Display a warning for all other usages like the one you suggested.

**Comment by jenweber** [comment] 2020-09-29 03:22
One possible approach here is to detect a phase, such as filtering for “so autistic” rather than just “autistic,” for example. That would capture some insensitive uses with fewer false positives for legitimate uses. This issue is closed, so I recommend opening a new issue for further discussion if that’s something anyone is interested in proposing.
